name: ${project.name}
main: net.daboross.bukkitdev.removegoditems.RemoveGodItemsPlugin
version: ${project.version}
author: Dabo Ross
description: ${project.description}
commands:
    rgireload:
        usage: /<command>
        permission: removegoditems.reload
